# Generated by Django 5.2.4 on 2025-12-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_approved',
        ),
    ]
