# Generated by Django 5.2.4 on 2025-12-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_community_donation_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='photo',
        ),
        migrations.AddField(
            model_name='community',
            name='photo_filename',
            field=models.CharField(blank=True, help_text="Digite o nome exato do arquivo localizado em 'static/img/communities/' (ex: 'Vila Pedra Mansa (Patu - RN).jpg').", max_length=255, null=True, verbose_name='Nome do Arquivo da Foto'),
        ),
    ]
